### ISSUE TITLE
Format des pages

### ISSUE THREAD

**Issue by fabio10000** [gen-classroom/projet-janssens_marques_lange_villagrasa#28]
En tant qu’utilisateur, j’aimerai pouvoir créer des pages contenant des métadonnées et du contenu.Par exemple, le format suivant répondrait à ce besoin:

```
titre: Mon premier article
auteur: Bertil Chapuis
date: 2021-03-10
---
# Mon premier article
## Mon sous-titre
Le contenu de mon article.

![Une image](./image.png)
```

Composant qui prend en entrée du texte et qui sépare les méthadonnées du texte

**Comment by TheSnekySnek** [comment]
Branch was merged
